[package]
name = "cultbot"
version = "0.1.0"
edition = "2024"

[dependencies]
aho-corasick = "1.1"
once_cell = "1.21"
rand = "0.9"
serenity = "0.12"
tokio = { version = "1.48", features = ["rt-multi-thread"] }
